// Generated by @adddog/monorepo-consistency
// Do not edit manually - regenerate with: mono knip generate
import { defineKnipConfig } from "@adddog/monorepo-consistency";

export default defineKnipConfig({
    entry: ["src/index.ts"],
    project: ["src/**/*.ts"],
}, {
    ignoreDependencies: [
        "@adddog/monorepo-consistency",
        "eslint",
        "@adddog/eslint",
        "@adddog/eslint-plugin-rules",
    ],
    ignoreBinaries: [
        "knip",
    ],
    entry: [
        "src/eslint.config.ts",
        "eslint.config.mjs",
    ],
    project: [
        "src/**/*.ts",
        "*.mjs",
    ],
});
